# Generated by Django 3.1.5 on 2021-01-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='f',
        ),
    ]
