# Generated by Django 3.1.5 on 2021-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_movies', '0002_delete_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='catagorie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
